#!/usr/bin/env node

const db = require('./DBTest');
console.log('db', db);
const fail = () => process.exit(1);
const success = () => process.exit(0);
const help = () => {
  console.log('This is the help message');
}

function testEmp() {
  db.readTestJSON('test.json')
  .then(() => success())
  .catch(e => {
    help();
    fail();
    console.error('err', e);
  });
}

testEmp();
